src/TipsAndTricks/TatBlog.WebApp/Areas/Admin/Controllers/CommentsController.cs
using FluentValidation;
using MapsterMapper;
using Microsoft.AspNetCore.Mvc;
using TatBlog.Core.Entities;
using TatBlog.Services.Blogs;
using TatBlog.WebApp.Areas.Admin.Models;

namespace TatBlog.WebApp.Areas.Admin.Controllers
{
	public class CommentsController : Controller
	{
        private readonly ILogger<CommentsController> _logger;
        private readonly IBlogRepository _blogRepository;
        private readonly IMapper _mapper;

        public CommentsController(
            IBlogRepository blogRepository,
            IMapper mapper)
        {
            _blogRepository = blogRepository;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index(
            [FromQuery(Name = "p")] int pageNumber = 1,
            [FromQuery(Name = "ps")] int pageSize = 10)
        {
            //_logger.LogInformation("Tạo điều kiện truy vấn");
            //// Sử dụng Mapster để tạo đối tượng PostQuery
            //// từ đối tượng PostFilterModel model
            //var postQuery = _mapper.Map<PostQuery>(model);

            //_logger.LogInformation("Lấy danh sách bài viết từ CSDL");
            //ViewBag.CategoriesList = await _blogRepository
            //    .GetPagedCategoriesAsync(pageNumber, pageSize);

            //_logger.LogInformation("Chuẩn bị dữ liệu trong ViewModel");
            //await PopulatePostFilterModeAsync(model);

            var model = await _blogRepository.GetPagedCommentAsync(pageNumber, pageSize);

            return View(model);
        }
      

        public async Task<IActionResult> ToggleApproved(int id = 0)
        {
            await _blogRepository.ToggleApprovedAsync(id);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> DeleteComment(int id = 0)
        {
            await _blogRepository.DeleteCommentByIdAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

src/TipsAndTricks/TatBlog.WebApp/Controllers/NewsletterController.cs
using Microsoft.AspNetCore.Mvc;
using TatBlog.Services.Subscribers;

namespace TatBlog.WebApp.Controllers
{
    public class NewsletterController : Controller
    {
        private readonly ISubscriberRepository _subcriberRepository;

        public NewsletterController(ISubscriberRepository subcriberRepository)
        {
            _subcriberRepository = subcriberRepository;
        }

        [HttpPost]
        public async Task<IActionResult> Subscribe(
            string email)
        {
            var subscribe = await _subcriberRepository.SubscribeAsync(email);
            //if (subscribe)
            //    await _subcriberRepository.SendEmailUnsubscribe(email);
            return View(subscribe);
        }

        public async Task<IActionResult> Unsubscribe()
        {
            return View();
        }
    }
}

src/TipsAndTricks/TatBlog.WebApp/Views/Shared/_Comment.cshtml
@model Comment
@{
	IList<Comment> commentsList = ViewBag.CommentsList;
}


<style>
	.be-comment-block {
		margin-bottom: 50px !important;
		border: 1px solid #edeff2;
		border-radius: 2px;
		padding: 50px 70px;
		border: 1px solid #ffffff;
	}

	.comments-title {
		color: #262626;
		margin-bottom: 15px;
	}



	.be-comment-content {
		margin-left: 80px;
	}

		.be-comment-content span {
			display: inline-block;
			width: 49%;
			margin-bottom: 15px;
		}

	.be-comment-content h4 {
		color: #383b43;
	}

	.be-comment-content span {
		display: inline-block;
		width: 49%;
		margin-bottom: 15px;
	}

	.be-comment-time {
		text-align: right;
	}

	.be-comment-time {
		color: #b4b7c1;
	}

	.be-comment-text {
		line-height: 18px;
		color: #7a8192;
		display: block;
		background: #f6f6f7;
		border: 1px solid #edeff2;
		padding: 15px 20px 20px 20px;
	}

	.form-group.fl_icon .icon {
		position: absolute;
		top: 1px;
		left: 16px;
		width: 48px;
		height: 48px;
		background: #f6f6f7;
		color: #b5b8c2;
		text-align: center;
		line-height: 50px;
		-webkit-border-top-left-radius: 2px;
		-webkit-border-bottom-left-radius: 2px;
		-moz-border-radius-topleft: 2px;
		-moz-border-radius-bottomleft: 2px;
		border-top-left-radius: 2px;
		border-bottom-left-radius: 2px;
	}

	.form-group .form-input {
		line-height: 50px;
		font-weight: 400;
		color: #b4b7c1;
		width: 100%;
		height: 50px;
		padding-left: 20px;
		padding-right: 20px;
		border: 1px solid #edeff2;
		border-radius: 3px;
	}

	.form-group textarea.form-input {
		height: 150px;
	}
</style>

<div class="border border-light w-75 p-3">
	<form class="row p-5"
		asp-area=""
		asp-controller="Blog"
		asp-action="Comments"
		enctype="multipart/form-data"
		method="post">
		<h5>Bình luận</h5>
		<input type="hidden" asp-for="PostId" />
		<div class="mb-3 col">
			<input asp-for="FullName" type="text" class="form-control" id="comment-fullname"  placeholder="Họ và tên">
		</div>
		<div class="mb-3 col">
			<div class="form-check form-check-inline">
				<input class="form-check-input" asp-for="Gender" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="male">
				<label class="form-check-label" for="inlineRadio1">Nam</label>
			</div>
			<div class="form-check form-check-inline">
				<input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="female">
				<label class="form-check-label" for="inlineRadio2">Nữ</label>
			</div>
		</div>
		<div class="w-100"></div>
		<div class="mb-3 col">
			<textarea asp-for="Description" type="text" class="form-control" id="" placeholder="Nội dung">
				</textarea>

		</div>
		<button type="submit" class="btn btn-primary">Submit</button>
	</form>
	<h3 class="comments-title">Comments (@commentsList.Count(x => x.Approved))</h3>
	@foreach (var item in commentsList)
		{
			@if (@item.Approved)
			{
				<div class="be-comment">
					<div class="be-comment-content">

						<span class="be-comment-name">
							<h4>@item.FullName</h4>
						</span>
						<span class="be-comment-time">
							<i class="fa fa-clock-o"></i>
							@item.PostedDate
						</span>

						<p class="be-comment-text">
							@item.Description
						</p>
					</div>
				</div>
			}
			
		

		}
		
	</div>

src/TipsAndTricks/TatBlog.WebApp/Views/Shared/_Header.cshtml
<header>
	<nav class="navbar navbar-expand-sm 
		navbar-toggleable-sm navbar-light 
		bg-white border-bottom box-shadow">
		<div class="container-fluid">
			<a class="navbar-brand" 
				asp-area="" 
				asp-controller="Blog" 
				asp-action="Index">
				Tips & Tricks
			</a>

			<button class="navbar-toggler"
				type="button"
				data-bs-toggle="collapse"
				data-bs-target=".navbar-collapse"
				aria-controls="navbarSupportedContent"
				aria-expanded="false"
				aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="navbar-collapse collapse
				d-sm-inline-flex
				justify-content-between">
				<ul class="navbar-nav flex-grow-1">
					<li class="nav-item">
						<a class="nav-link text-dark"
							asp-area=""
							asp-controller="Blog"
							asp-action="Index">
							Trang chủ
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link text-dark"
							asp-area=""
							asp-controller="Blog"
							asp-action="Contact"
							title="Xem thông tin liên lạc và góp ý">
							Liên hệ
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link text-dark"
							asp-area=""
							asp-controller="Blog"
							asp-action="About"
							title="Thông tin về TAT Blog">
							Giới thiệu
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link text-dark"
							asp-area=""
							asp-controller="Blog"
							asp-action="Rss"
							title="Tải danh sách bài viết mới">
							RSS Feed
						</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>
</header>

src/TipsAndTricks/TatBlog.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["PageTitle"] - Tips & Tricks Blog</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/css/main.css" asp-append-version="true" />

    @await RenderSectionAsync("style", required: false)
</head>
<body>
    <!-- Thanh tiêu đề, logo, menu -->
    <partial name="_Header" />

    <div class="container-fluid">
        <div class="row">
            <div class="col-9">
                <!-- Phần nội dung chính -->
                @RenderBody()
            </div>
            <div class="col-3 border-start">
                <!-- Danh sách chuyên mục, tag cloud, ... -->
                <partial name="_SideBar" />
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid text-center">
            &copy; 2023 - Tips & Tricks Blog
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/main.js" asp-append-version="true"></script>

    @await RenderSectionAsync("scripts", false);
</body>
</html>

src/TipsAndTricks/TatBlog.WebApp/Views/Shared/_NewsletterForm.cshtml
<div class="mb-4">
	<form class="form-inline" method="POST"
        asp-area=""
        asp-controller="Newsletter" 
        asp-action="Subscribe" 
                    >
        <div class="input-group  mb-3">
            <input type="email" class="form-control" id="email" name="email" placeholder="Email">
            <button type="submit" class="btn btn-primary">Đăng ký</button>
        </div>
    </form>
</div>

src/TipsAndTricks/TatBlog.WebApp/Views/Shared/_SearchForm.cshtml
<div class="mb-4">
	<form asp-area="" asp-controller="Blog"
		asp-action="Index"
		method="get">
		<div class="input-group mb-3">
			<input type="text"
				class="form-control"
				name="k"
				placeholder="Enter keyword"
				aria-label="Enter keyword"
				aria-describedby="btnSearchPost"/>
			<button class="btn btn-outline-secondary"
				type="button"
				id="btnSearchPost">
				<i class="fa fa-search"></i>
			</button>
		</div>
	</form>
</div>

src/TipsAndTricks/TatBlog.WebApp/Views/Shared/_SideBar.cshtml
<div class="my-4">
	<!-- Form tìm kiếm -->
	<partial name="_SearchForm"></partial>

	<!-- Các chuyên mục/chủ đề -->
	@await Component.InvokeAsync("CategoriesWidget")

	<!-- Top bài viết nổi bật-->
	@await Component.InvokeAsync("FeaturedPostsWidget")

	<!-- Ngẫu nhiên 5 bài viết-->
	@await Component.InvokeAsync("RandomPostsWidget")

	<!-- Đăng ký nhận tin mới -->
	<h3 class="text-success mb-2">
		Đăng ký nhận tin mới
	</h3>
	<partial name="_NewsletterForm" />

	<!-- Tag cloud -->
	<h1>
		@await Component.InvokeAsync("TagCloudWidget")
	</h1>

	<!-- Archives -->
	@await Component.InvokeAsync("ArchivesWidget")

	<!-- Top Author -->
	@await Component.InvokeAsync("BestAuthorsWidget")
</div>