src/TipsAndTricks/TatBlog.WebApp/Areas/Admin/Controllers/SubscribersController.cs
using FluentValidation;
using FluentValidation.AspNetCore;
using MapsterMapper;
using Microsoft.AspNetCore.Mvc;
using System.Security.Cryptography.Pkcs;
using TatBlog.Core.Entities;
using TatBlog.Services.Authors;
using TatBlog.Services.Blogs;
using TatBlog.Services.Media;
using TatBlog.Services.Subscribers;
using TatBlog.WebApp.Areas.Admin.Models;

namespace TatBlog.WebApp.Areas.Admin.Controllers
{
	public class SubscribersController : Controller
	{
		private readonly ILogger<SubscribersController> _logger;
		private readonly IBlogRepository _blogRepository;
		private readonly IAuthorRepository _authorRepository;
		private readonly ISubscriberRepository _subscriberRepository;
		private readonly IMapper _mapper;
		private readonly IMediaManager _mediaManager;
		private readonly IValidator<SubscriberEditModel> _validator;

		public SubscribersController(
			ILogger<SubscribersController> logger,
			IBlogRepository blogRepository,
			IAuthorRepository authorRepository,
			ISubscriberRepository subscriberRepository,
			IMapper mapper, IMediaManager mediaManager,
			IValidator<SubscriberEditModel> validator)
		{
			_logger = logger;
			_blogRepository = blogRepository;
			_authorRepository = authorRepository;
			_mapper = mapper;
			_mediaManager = mediaManager;
			_validator = validator;
			_subscriberRepository = subscriberRepository;
		}

		public async Task<IActionResult> Index(
			[FromQuery(Name = "p")] int pageNumber = 1,
			[FromQuery(Name = "ps")] int pageSize = 5)
		{

			var model = await _subscriberRepository.GetPagedSubscribersAsync(pageNumber, pageSize);

			return View(model);
		}

        [HttpGet]
        public async Task<IActionResult> Edit(int id = 0)
        {
            // Id = 0 <=> Thêm bài viết mới
            // Id > 0: Đọc bài viết từ CSDL
            var subscriber = id > 0
                ? await _subscriberRepository.GetSubscriberByIdAsync(id)
                : null;

            // Tạo view model từ dữ liệu bài viết
            var model = subscriber == null
                ? new SubscriberEditModel()
                : _mapper.Map<SubscriberEditModel>(subscriber);

            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(
            SubscriberEditModel model)
        {
            var validationResult = await _validator.ValidateAsync(model);

            if (!validationResult.IsValid)
            {
                validationResult.AddToModelState(ModelState);
            }

            var subscriber = model.Id > 0
                ? await _subscriberRepository.GetSubscriberByIdAsync(model.Id)
                : null;

                _mapper.Map(model, subscriber);
			subscriber.UnsubscribeDate = DateTime.Now;

			var type = subscriber.TypeReason == null || subscriber.TypeReason == true
				? true 
				: false;

            await _subscriberRepository.ToggleBlockSubscriberAsync(subscriber, type);

            return RedirectToAction(nameof(Index));

        }

    }
}

src/TipsAndTricks/TatBlog.WebApp/Areas/Admin/Views/Subscribers/Edit.cshtml
@model TatBlog.WebApp.Areas.Admin.Models.SubscriberEditModel

@{
	ViewData["PageTitle"] = "Chặn/Bỏ chặn người đăng ký";
	var stateList = new List<SelectListItem>
	{
		new SelectListItem("Người dùng hủy đăng ký", "false"),
		new SelectListItem("Người dùng bị chặn", "true"),

	};
}

<h1>Chặn/Bỏ chặn người đăng ký</h1>

<form asp-area="Admin"
	asp-controller="Subscribers"
	asp-action="Edit"
	enctype="multipart/form-data"
	method="post">
	
	<div asp-validation-summary="ModelOnly"></div>
	<input type="hidden" asp-for="Id"/>
	<input type="hidden" asp-for="Email" />
	<input type="hidden" asp-for="SubscribeDate" />
	<input type="hidden" asp-for="UnsubscribeDate" />

	<div class="row mb-3">
		<label asp-for="TypeReason"
	  class="col-sm-2 col-form-label"></label>
		<div class="col-sm-10">
			<select class="form-control"
					asp-for="TypeReason" asp-items="stateList" name="typeReason">
				<option value="">-- Chọn loại đăng ký --</option>
			</select>
			<span asp-validation-for="TypeReason"
	  class="text-danger"></span>
		</div>
	</div>

	<div class="row mb-3">
		<label asp-for="ResonUnsubscribe"
			class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
			<input type="text" class="form-control" asp-for="ResonUnsubscribe" name="reasonUnsub" />
			<span asp-validation-for="ResonUnsubscribe"
	  class="text-danger"></span>
			
			</div>
	</div>

	<div class="row mb-3">
		<label asp-for="Notes"
	  class="col-sm-2 col-form-label"></label>
		<div class="col-sm-10">
			<textarea class="form-control"
					  asp-for="Notes"></textarea>
			<span asp-validation-for="Notes"
	  class="text-danger"></span>
		</div>
	</div>

	<div class="text-center">
		<button type="submit" class="btn btn-primary">
			Lưu các thay đổi
		</button>

		<a asp-area="Admin"
		   asp-controller="Subscribers"
		   asp-action="Index"
	 class="btn btn-danger">
			Hủy & Quay lại
		</a>
	</div>
</form>


@section scripts
{
	<partial name="_ValidationScriptsPartial" />

	<script src="~/lib/speakingurl/speakingurl.min.js"></script>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>

	<script>
		$(function() {
			$('#Name').change(function () {
				var slug = getSlug(this.value);
				$('#UrlSlug').val(slug).trigger('blur');
			})
		});
	</script>

	<script type="text/javascript">
		$('select[name=typeReason] option').filter(':selected').val()
		$('typeReason').on('change', function () {
			console.log(this.value);
			if (this.value == "true")
				$("reasonUnsub").prop('disabled', true);
		});
	</script>
}

src/TipsAndTricks/TatBlog.WebApp/Areas/Admin/Views/Subscribers/Index.cshtml
@model IPagedList<Subscriber>
@{
    ViewData["PageTitle"] = "Danh sách người đăng ký";
    var subscribersList = Model;
}

<h1>
    Danh sách người đăng ký
</h1>


<style>
    tr th:nth-last-child(-n+2) {
        text-align: center;
    }

    tr td:nth-last-child(-n+2) {
        text-align: center;
    }
</style>


@if (subscribersList != null && subscribersList.Count > 0)
{
    <table class="table table-responsive table-striped">
        <thead>
            <tr>
                <th>Email</th>
                <th>Ngày đăng ký</th>
                <th>Trạng thái</th>
                <th>Ngày hủy đăng ký</th>
                <th>Loại hủy</th>
                <th>Xóa</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var subscriber in subscribersList)
            {
                <tr>
                    <td>
                        <a asp-area="Admin"
                   asp-controller="Subscribers"
                   asp-action="Edit"
                   asp-route-id="@subscriber.Id">
                            @subscriber.Email
                        </a>

                        <p class="text-muted">
                            @subscriber.Notes
                        </p>
                    </td>
                    <td>
                        <p class="text-bold">
                            @subscriber.SubscribeDate
                        </p>
                    </td>
                    <td>
                        <a asp-area="Admin"
                            asp-controller="Subscribers"
                   asp-action="BlockSubscriber"
                   asp-route-id="@subscriber.Id"
                           class="btn btn-sm @(subscriber.TypeReason == null ? "btn-success" : subscriber.TypeReason == true ? "btn-secondary" : "btn-danger")"
                           onclick="">
                            @if (subscriber.TypeReason == null)
                            {
                                <i class="fa fa-check"></i>
                            }
                            else if (subscriber.TypeReason == true)
                                        {
                                        <i class="fa fa-times"></i>
                                        }
                            else
                            {
                                <i class="fa fa-ban"></i>
                            }
                        </a>
                    </td>

                    <td>
                        @subscriber.UnsubscribeDate
                    </td>
                    <td>
                        @subscriber.ResonUnsubscribe
                    </td>

                    <td>
                        <a asp-area="Admin"
                   asp-controller="Subscribers"
                   asp-action="DeleteSubscriber"
                   asp-route-id="@subscriber.Id"
                           class="btn btn-sm btn-danger"
                           onclick="return confirm('Bạn muốn xóa người đăng ký này không ?');">
                            <i class="fa fa-trash"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <script>
    </script>

    <partial name="_PagerAdmin" model="@subscribersList"></partial>
}
else
{
    <h1 class="text-danger">
        Không tìm thấy người đăng ký nào
    </h1>
}

src/TipsAndTricks/TatBlog.WebApp/Areas/Admin/Views/Subscribers/_PagerAdmin.cshtml
@model IPagedList<Subscriber>

@{
	var actionName = "Index";
	var slug = "";
}

@if (Model.PageCount > 1)
{
	<div class="text-center my-4">
		@if (Model.HasPreviousPage)
		{
			<a asp-area="Admin"
	   asp-controller="Subscribers"
	   asp-action="@actionName"
	   asp-route-slug="@slug"
	   asp-route-p="@(Model.PageNumber - 1)"
	   asp-route-ps="@Model.PageSize"
			class="btn btn-info">
				<i class="fa fa-arrow-left"></i>
				Trang trước
			</a>
		}
		else
		{
			<button type="button"
					class="btn btn-outline-secondary"
					disabled>
				<i class="fa fa-arrow-left"></i>
				Trang trước
			</button>
		}

		@if (Model.HasNextPage)
		{
			<a asp-area="Admin"
	   asp-controller="Subscribers"
	   asp-action="Index"
	   asp-route-slut="@slug"
	   asp-route-p="@(Model.PageNumber + 1)"
	   asp-route-ps="@Model.PageSize"
			class="btn btn-info">
				<i class="fa fa-arrow-right"></i>
				Trang sau
			</a>
		}
		else
		{
			<button type="button"
					class="btn btnbtn-outline-secondary"
					disabled>
				Trang sau
				<i class="fa fa-arrow-right"></i>
			</button>
		}
	</div>
}