src/TipsAndTricks/TatBlog.WebApp/Areas/Admin/Controllers/AuthorsController.cs
using FluentValidation;
using FluentValidation.AspNetCore;
using MapsterMapper;
using Microsoft.AspNetCore.Mvc;
using TatBlog.Core.DTO;
using TatBlog.Core.Entities;
using TatBlog.Services.Authors;
using TatBlog.Services.Blogs;
using TatBlog.Services.Media;
using TatBlog.WebApp.Areas.Admin.Models;

namespace TatBlog.WebApp.Areas.Admin.Controllers
{
	public class AuthorsController : Controller
	{
        // AuthorController
        private readonly ILogger<PostsController> _logger;
        private readonly IBlogRepository _blogRepository;
        private readonly IAuthorRepository _authorRepository;
        private readonly IMapper _mapper;
        private readonly IMediaManager _mediaManager;
        private readonly IValidator<AuthorEditModel> _validator;


        public AuthorsController(
            ILogger<PostsController> logger,
            IBlogRepository blogRepository,
            IAuthorRepository authorRepository,
            IMapper mapper,
            IMediaManager mediaManager,
            IValidator<AuthorEditModel> validator)
        {
            _logger = logger;
            _blogRepository = blogRepository;
            _authorRepository = authorRepository;
            _mapper = mapper;
            _mediaManager = mediaManager;
            _validator = validator;

        }

        public async Task<IActionResult> Index(
            [FromQuery(Name = "p")] int pageNumber = 1,
            [FromQuery(Name = "ps")] int pageSize = 5)
        {

            var model = await _authorRepository.GetPagedAuthorsAsync(pageNumber, pageSize);

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id = 0)
        {
            // Id = 0 <=> Thêm bài viết mới
            // Id > 0: Đọc bài viết từ CSDL
            var author = id > 0
                ? await _authorRepository.GetAuthorByIdAsync(id)
                : null;

            // Tạo view model từ dữ liệu bài viết
            var model = author == null
                ? new AuthorEditModel()
                : _mapper.Map<AuthorEditModel>(author);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(
            [FromServices] IValidator<AuthorEditModel> validator,
            AuthorEditModel model)
        {
            var validationResult = await validator.ValidateAsync(model);

            if (!validationResult.IsValid)
            {
                validationResult.AddToModelState(ModelState);
            }

            //if (!ModelState.IsValid)
            //{
            //    await PopulatePostEditModeAsync(model);
            //    return View(model);
            //}

            var author = model.Id > 0
                ? await _authorRepository.GetAuthorByIdAsync(model.Id)
                : null;

            if (author == null)
            {
                author = _mapper.Map<Author>(model);

                author.Id = 0;
                author.JoinedDate = DateTime.Now;
            }
            else
            {
                _mapper.Map(model, author);
            }

            // Nếu người dùng có upload hình ảnh minh họa cho bài viết
            if (model.ImageFile?.Length > 0)
            {
                // Thì thực hiện lưu tập tin vào thư mục uploads
                var newImagePath = await _mediaManager.SaveFileAsync(
                    model.ImageFile.OpenReadStream(),
                    model.ImageFile.FileName,
                    model.ImageFile.ContentType);

                // Nếu lưu thành công, xóa tập tin hình ảnh cũ (nếu có)
                if (!string.IsNullOrWhiteSpace(newImagePath))
                {
                    await _mediaManager.DeleteFileAsync(author.ImageUrl);
                    author.ImageUrl = newImagePath;
                }
            }

            await _authorRepository.CreateOrUpdateAuthorAsync(author);

            return RedirectToAction(nameof(Index));

        }

        [HttpPost]
        public async Task<IActionResult> VerifyAuthorSlug(
            int id, string urlSlug)
        {
            var slugExisted = await _authorRepository
                .IsAuthorSlugExistedAsync(id, urlSlug);

            return slugExisted
                ? Json($"Slug '{urlSlug}' đã được sử dụng")
                : Json(true);
        }

        public async Task<IActionResult> DeleteAuthor(int id)
        {
            await _authorRepository.DeleteAuthorByIdAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

src/TipsAndTricks/TatBlog.WebApp/Areas/Admin/Controllers/CommentsController.cs
using FluentValidation;
using MapsterMapper;
using Microsoft.AspNetCore.Mvc;
using TatBlog.Core.Entities;
using TatBlog.Services.Blogs;
using TatBlog.WebApp.Areas.Admin.Models;

namespace TatBlog.WebApp.Areas.Admin.Controllers
{
	public class CommentsController : Controller
	{
        private readonly ILogger<CommentsController> _logger;
        private readonly IBlogRepository _blogRepository;
        private readonly IMapper _mapper;

        public CommentsController(
            IBlogRepository blogRepository,
            IMapper mapper)
        {
            _blogRepository = blogRepository;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index(
            [FromQuery(Name = "p")] int pageNumber = 1,
            [FromQuery(Name = "ps")] int pageSize = 10)
        {
            //_logger.LogInformation("Tạo điều kiện truy vấn");
            //// Sử dụng Mapster để tạo đối tượng PostQuery
            //// từ đối tượng PostFilterModel model
            //var postQuery = _mapper.Map<PostQuery>(model);

            //_logger.LogInformation("Lấy danh sách bài viết từ CSDL");
            //ViewBag.CategoriesList = await _blogRepository
            //    .GetPagedCategoriesAsync(pageNumber, pageSize);

            //_logger.LogInformation("Chuẩn bị dữ liệu trong ViewModel");
            //await PopulatePostFilterModeAsync(model);

            var model = await _blogRepository.GetPagedCommentAsync(pageNumber, pageSize);

            return View(model);
        }
      

        public async Task<IActionResult> ToggleApproved(int id = 0)
        {
            await _blogRepository.ToggleApprovedAsync(id);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> DeleteComment(int id = 0)
        {
            await _blogRepository.DeleteCommentByIdAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

src/TipsAndTricks/TatBlog.WebApp/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using TatBlog.Services.Authors;
using TatBlog.Services.Blogs;
using TatBlog.Services.Subscribers;

namespace TatBlog.WebApp.Areas.Admin.Controllers
{
	public class DashboardController : Controller
	{
		private readonly IBlogRepository _blogRepository;
		private readonly ISubscriberRepository _subscriberRepository;
		private readonly IAuthorRepository _authorRepository;

        public DashboardController(
			IBlogRepository blogRepository,
			ISubscriberRepository subscriberRepository,
			IAuthorRepository authorRepository)
		{
			_blogRepository = blogRepository;
            _subscriberRepository = subscriberRepository;
            _authorRepository = authorRepository;
        }

		public async Task<IActionResult> Index()
		{
			ViewBag.TotalPosts = await _blogRepository.GetTotalPostsAsync();
			ViewBag.NumberPostsUnpublished = await _blogRepository.NumberPostsUnpublishedAsync();
			ViewBag.NumberCategories = await _blogRepository.NumberCategoriesAsync();
			ViewBag.NumberAuthors = await _authorRepository.NumberAuthorsAsync();
			ViewBag.NumberCommentsUnapproved = await _blogRepository.NumberCommentsUnApprovedAsync();
			ViewBag.NumberSubscribers = await _subscriberRepository.NumberSubscribersAsync();
			ViewBag.NumberSubscribersToday = await _subscriberRepository.NumberSubscribersTodayAsync();
            return View();
		}
	}
}

src/TipsAndTricks/TatBlog.WebApp/Areas/Admin/Controllers/TagsController.cs
using FluentValidation;
using FluentValidation.AspNetCore;
using MapsterMapper;
using Microsoft.AspNetCore.Mvc;
using TatBlog.Core.Entities;
using TatBlog.Services.Blogs;
using TatBlog.WebApp.Areas.Admin.Models;

namespace TatBlog.WebApp.Areas.Admin.Controllers
{
	public class TagsController : Controller
	{
		private readonly ILogger<TagEditModel> _logger;
		private readonly IValidator<TagEditModel> _validator;
		private readonly IBlogRepository _blogRepository;
		private readonly IMapper _mapper;

		public TagsController(
			IBlogRepository blogRepository,
			IMapper mapper,
			IValidator<TagEditModel> validator)
		{
			_blogRepository = blogRepository;
			_mapper = mapper;
			_validator = validator;
		}

		public async Task<IActionResult> Index(
			[FromQuery(Name = "p")] int pageNumber = 1,
			[FromQuery(Name = "ps")] int pageSize = 5)
		{
			//_logger.LogInformation("Tạo điều kiện truy vấn");
			//// Sử dụng Mapster để tạo đối tượng PostQuery
			//// từ đối tượng PostFilterModel model
			//var postQuery = _mapper.Map<PostQuery>(model);

			//_logger.LogInformation("Lấy danh sách bài viết từ CSDL");
			//ViewBag.CategoriesList = await _blogRepository
			//    .GetPagedCategoriesAsync(pageNumber, pageSize);

			//_logger.LogInformation("Chuẩn bị dữ liệu trong ViewModel");
			//await PopulatePostFilterModeAsync(model);

			var model = await _blogRepository.GetPagedTagsAsync(pageNumber, pageSize);

			return View(model);
		}

		[HttpGet]
		public async Task<IActionResult> Edit(int id = 0)
		{
			// Id = 0 <=> Thêm bài viết mới
			// Id > 0: Đọc bài viết từ CSDL
			var tag = id > 0
				? await _blogRepository.GetTagByIdAsync(id)
				: null;

			// Tạo view model từ dữ liệu bài viết
			var model = tag == null
				? new TagEditModel()
				: _mapper.Map<TagEditModel>(tag);

			// Gán các giá trị khác cho view model
			//await PopulateCategoryEditModeAsync(model);

			return View(model);
		}


		[HttpPost]
		public async Task<IActionResult> Edit(
			[FromServices] IValidator<TagEditModel> validator,
			TagEditModel model)
		{
			var validationResult = await validator.ValidateAsync(model);

			if (!validationResult.IsValid)
			{
				validationResult.AddToModelState(ModelState );
			}

			var tag = model.Id > 0
				? await _blogRepository.GetTagByIdAsync(model.Id)
				: null;

			if (tag == null)
			{
				tag = _mapper.Map<Tag>(model);

				tag.Id = 0;
			}
			else
			{
				_mapper.Map(model, tag);
			}


			await _blogRepository.CreateOrUpdateTagAsync(tag);

			return RedirectToAction(nameof(Index));

		}

		[HttpPost]
		public async Task<IActionResult> VerifyTagSlug(
			int id, string urlSlug)
		{
			var slugExisted = await _blogRepository
				.IsTagSlugExistedAsync(id, urlSlug);

			return slugExisted
				? Json($"Slug '{urlSlug}' đã được sử dụng")
				: Json(true);
		}

		public async Task<IActionResult> DeleteTag(int id = 0)
		{
			await _blogRepository.DeleteTagByIdAsync(id);
			return RedirectToAction(nameof(Index));
		}
	}
}

src/TipsAndTricks/TatBlog.WebApp/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["PageTitle"] - Tips & Tricks Blog</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/css/main.css" asp-append-version="true" />

    @await RenderSectionAsync("style", required: false)
</head>
<body>
    <!-- Thanh tiêu đề, logo, menu -->
    <partial name="_NavBar" />

    <div class="container-fluid">
        <!-- Phần nội dung chính -->
        @RenderBody()
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid text-center">
            &copy; 2023 - Tips & Tricks Blog
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/main.js" asp-append-version="true"></script>

    @await RenderSectionAsync("scripts", false);
</body>
</html>

src/TipsAndTricks/TatBlog.WebApp/Areas/Admin/Views/Shared/_NavBar.cshtml
<header>
	<nav class="navbar navbar-expand-sm 
		navbar-toggleable-sm navbar-light 
		bg-white border-bottom box-shadow">
		<div class="container-fluid">
			<a class="navbar-brand" 
				asp-area="Admin" 
				asp-controller="Dashboard" 
				asp-action="Index">
				Tips & Tricks
			</a>

			<button class="navbar-toggler"
				type="button"
				data-bs-toggle="collapse"
				data-bs-target=".navbar-collapse"
				aria-controls="navbarSupportedContent"
				aria-expanded="false"
				aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="navbar-collapse collapse
				d-sm-inline-flex
				justify-content-between">
				<ul class="navbar-nav flex-grow-1">
					<li class="nav-item">
						<a class="nav-link text-dark"
							asp-area="Admin"
							asp-controller="Categories"
							asp-action="Index"
							title="Xem danh sách chủ đè">
							Chủ đề
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link text-dark"
						   asp-area="Admin"
							asp-controller="Authors"
							asp-action="Index"
							title="Xem danh sách tác giả">
							Tác giả
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link text-dark"
						   asp-area="Admin"
							asp-controller="Tags"
							asp-action="Index"
							title="Xem danh sách thẻ/từ khóa">
							Thẻ
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link text-dark"
						   asp-area="Admin"
							asp-controller="Posts"
							asp-action="Index"
							title="Xem danh sách bài viết">
							Bài viết
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link text-dark"
							asp-area="Admin"
							asp-controller="Comments"
							asp-action="Index"
							title="Xem danh sách bình luận">
							Bình luận
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link text-dark"
						   asp-area="Admin"
						   asp-controller="Subscribers"
						   asp-action="Index"
							title="Xem danh sách đăng ký">
							Đăng ký tin tức
						</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>
</header>